apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-14T02:49:22Z"
  generateName: testing-crpd1-0-
  labels:
    app: crpd1-0
    cerebrum.juniper.net/instanceSelector: crpd1-0
    cerebrum.juniper.net/instanceType: Crpd
    controller-revision-hash: testing-crpd1-0-8d8f5d7bd
    crpd.cerebrum.juniper.net/crpd: crpd1-0
    crpd.cerebrum.juniper.net/crpdNamespace: testing
    name: crpd1-0
    statefulset.kubernetes.io/pod-name: testing-crpd1-0-0
  name: testing-crpd1-0-0
  namespace: jcnr
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: testing-crpd1-0
    uid: d003def0-5e22-4dfe-b14f-5fecfe685058
  uid: 4ff27736-41cb-4841-b100-e19725e808d9
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: cerebrum.juniper.net/instanceType
            operator: In
            values:
            - Crpd
        topologyKey: kubernetes.io/hostname
  containers:
  - image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpd:23.4R1.9
    imagePullPolicy: IfNotPresent
    name: crpd
    ports:
    - containerPort: 179
      hostPort: 179
      protocol: TCP
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/certs
      name: certs
    - mountPath: /config
      name: config
    - mountPath: /var/run
      name: var-run-crpd
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8wqzw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostname: testing-crpd1-0-0
  initContainers:
  - env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: BASE_CONFIG_DIR
      value: /config
    - name: POD_IPS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIPs
    - name: CRPD_INSTANCE_NAME
      value: crpd1-0
    - name: CRPD_INSTANCE_NAMESPACE
      value: testing
    image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/cerebrum-crpd-init:61678478c2
    imagePullPolicy: Always
    name: init
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/certs
      name: certs
    - mountPath: /config
      name: config
    - mountPath: /var/run/vrouter
      name: var-run-vrouter
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8wqzw
      readOnly: true
  - env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: CRPD_PERSONALITY
      value: jcnr
    - name: CRPD_CONFIG_DIR
      value: /config
    - name: IS_MASTER
      value: "False"
    - name: CRPD_CONFIG_TEMPLATE
      value: /etc/jcnr/crpdconfig
    - name: PRIMARY_CNI
      value: "False"
    - name: BGP_CONNECT_PORT
      value: "179"
    - name: BGP_LISTEN_PORT
      value: "178"
    - name: SRGB_START_LABEL
      value: "400000"
    - name: SRGB_INDEX_RANGE
      value: "4000"
    - name: SYSLOG_REMOTE_DEST
      value: '@127.0.0.1:50055'
    - name: CNI_LOG_FILE_SIZE
      value: "1"
    - name: CNI_LOG_FILE_COUNT
      value: "10"
    - name: CNI_LOG_PATH
      value: /var/log/jcnr/
    - name: CNI_LOG_LEVEL
      value: info
    image: hub.jnprlabs.net/cerebrum/junos-docker-local/warthog/amd64/jcnr-cni:23.4-20231208-1ef2250
    imagePullPolicy: IfNotPresent
    name: install-cni
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_ADMIN
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /host
      name: cni
    - mountPath: /var/run
      name: var-run-crpd
    - mountPath: /etc/localtime
      name: host-time
    - mountPath: /etc/secrets
      name: secrets
    - mountPath: /etc/jcnr
      name: jcnr-config-generated
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8wqzw
      readOnly: true
  nodeName: smane-csrx-new
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: crpd
  serviceAccountName: crpd
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: certs
  - hostPath:
      path: /var/run/vrouter
      type: DirectoryOrCreate
    name: var-run-vrouter
  - emptyDir: {}
    name: config
  - hostPath:
      path: /
      type: ""
    name: cni
  - hostPath:
      path: /var/run/crpd
      type: DirectoryOrCreate
    name: var-run-crpd
  - hostPath:
      path: /etc/localtime
      type: ""
    name: host-time
  - name: secrets
    secret:
      defaultMode: 420
      secretName: jcnr-secrets
  - configMap:
      defaultMode: 420
      name: jcnr-config-generated
    name: jcnr-config-generated
  - name: kube-api-access-8wqzw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-14T02:54:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-14T02:54:04Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-14T02:54:04Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-14T02:54:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://d150debcadb33cbcc8760c9e0c5e85782de3522b4a0cb3e9497ebef71603f152
    image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpd:23.4R1.9
    imageID: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpd@sha256:6a29849e1b1a8a7e7d5c8125b13afb388aac1e051191874453ecdc5cadb0a661
    lastState: {}
    name: crpd
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-14T02:54:03Z"
  hostIP: 10.87.76.26
  initContainerStatuses:
  - containerID: cri-o://af19d66f8324d53a156a4542b2df5af8a7bc2c65fc658733aef9822f8e1c717c
    image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/cerebrum-crpd-init:61678478c2
    imageID: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/cerebrum-crpd-init@sha256:6b58a8e8564326cbcf05d578a085fb4bae24f2480bbde1e33ef3f6b18f938aff
    lastState: {}
    name: init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://af19d66f8324d53a156a4542b2df5af8a7bc2c65fc658733aef9822f8e1c717c
        exitCode: 0
        finishedAt: "2024-01-14T02:54:01Z"
        reason: Completed
        startedAt: "2024-01-14T02:54:01Z"
  - containerID: cri-o://764c9ed94090103c6e2c40a743215c3b3dc8c2072050d3e82d14c2e3361fd39e
    image: hub.jnprlabs.net/cerebrum/junos-docker-local/warthog/amd64/jcnr-cni:23.4-20231208-1ef2250
    imageID: hub.jnprlabs.net/cerebrum/junos-docker-local/warthog/amd64/jcnr-cni@sha256:313254c09611d305ffe2c13463b090eb9d69d9575db4c9c90905acca61196e2d
    lastState: {}
    name: install-cni
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://764c9ed94090103c6e2c40a743215c3b3dc8c2072050d3e82d14c2e3361fd39e
        exitCode: 0
        finishedAt: "2024-01-14T02:54:03Z"
        reason: Completed
        startedAt: "2024-01-14T02:54:02Z"
  phase: Running
  podIP: 10.87.76.26
  podIPs:
  - ip: 10.87.76.26
  qosClass: BestEffort
  startTime: "2024-01-14T02:54:00Z"
