apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"webhook","app.kubernetes.io/created-by":"cerebrum","app.kubernetes.io/instance":"webhook-service","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"service","app.kubernetes.io/part-of":"cerebrum"},"name":"cerebrum-webhook-service","namespace":"cerebrum-system"},"spec":{"ports":[{"port":443,"protocol":"TCP","targetPort":9443}],"selector":{"control-plane":"controller-manager"}}}
  creationTimestamp: "2024-01-06T00:34:10Z"
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: cerebrum
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: cerebrum
  name: cerebrum-webhook-service
  namespace: cerebrum-system
  uid: bb2f406f-d5e5-4b51-8a79-d61b340cb90a
spec:
  clusterIP: 10.100.183.133
  clusterIPs:
  - 10.100.183.133
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
