apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-12-27T09:47:46Z"
  generateName: contrail-k8s-deployer-67c445564f-
  labels:
    app: contrail-k8s-deployer
    pod-template-hash: 67c445564f
  name: contrail-k8s-deployer-67c445564f-8k7kk
  namespace: contrail-deploy
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: contrail-k8s-deployer-67c445564f
    uid: 3529ae9f-b6ee-407c-94f1-c9c94b84e3c0
  uid: 535131bc-6134-4efc-b92a-d29cd8fcf540
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
  containers:
  - command:
    - sh
    - -c
    - /manager --metrics-addr 127.0.0.1:8081 --headless-mode true
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-k8s-deployer:master
    imagePullPolicy: IfNotPresent
    name: contrail-k8s-deployer
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/localtime
      name: host-time
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: cert
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-52854
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - command:
    - kubectl
    - apply
    - --server-side=true
    - --force-conflicts
    - -k
    - /distributed-crd
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-k8s-distributed-crdloader:master
    imagePullPolicy: IfNotPresent
    name: contrail-k8s-crdloader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/localtime
      name: host-time
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-52854
      readOnly: true
  nodeName: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: contrail-deploy-serviceaccount
  serviceAccountName: contrail-deploy-serviceaccount
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/localtime
      type: ""
    name: host-time
  - name: cert
    secret:
      defaultMode: 420
      secretName: webhook-server-cert
  - name: kube-api-access-52854
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:47:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:47:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:47:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:47:47Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://20a432fce27230ed6d1a6228207d7b55102d377f9a920a3da4d3005fc797fa4c
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-k8s-deployer:master
    imageID: 9b0e0429bcecf087ae0e8d774198bb2a9394b447786a0a7c623aecdabe5d3913
    lastState: {}
    name: contrail-k8s-deployer
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-12-27T09:47:54Z"
  hostIP: 192.168.1.3
  initContainerStatuses:
  - containerID: cri-o://1c9f6012f6f06666c8ff9a05fb2e6f17045761ba94dd53b29dca51f046f54a67
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/contrail-k8s-distributed-crdloader:master
    imageID: c204c2b326cafc6d16ab2742e9d7de17140dae500f425b1ea5ca30391205e267
    lastState: {}
    name: contrail-k8s-crdloader
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://1c9f6012f6f06666c8ff9a05fb2e6f17045761ba94dd53b29dca51f046f54a67
        exitCode: 0
        finishedAt: "2023-12-27T09:47:51Z"
        reason: Completed
        startedAt: "2023-12-27T09:47:50Z"
  phase: Running
  podIP: 192.168.1.3
  podIPs:
  - ip: 192.168.1.3
  qosClass: BestEffort
  startTime: "2023-12-27T09:47:47Z"
