apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: dc27c256edcb56e6af4ea2e3b07985310442b3d76e7c473fd48b920fa7545bf0
    cni.projectcalico.org/podIP: 192.168.0.42/32
    cni.projectcalico.org/podIPs: 192.168.0.42/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.42"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.42"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-01T16:11:54Z"
  generateName: cert-manager-cainjector-bdd866bd4-
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/version: v1.12.0
    pod-template-hash: bdd866bd4
  name: cert-manager-cainjector-bdd866bd4-ssxln
  namespace: cert-manager
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cert-manager-cainjector-bdd866bd4
    uid: 1d3c1b85-b684-424a-9a7d-bfd327ccab2d
  uid: 41ffaa5e-6808-4748-b1f7-d492b91050dd
spec:
  containers:
  - args:
    - --v=2
    - --leader-election-namespace=kube-system
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: quay.io/jetstack/cert-manager-cainjector:v1.12.0
    imagePullPolicy: IfNotPresent
    name: cert-manager-cainjector
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zwbpn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: cert-manager-cainjector
  serviceAccountName: cert-manager-cainjector
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-zwbpn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-01T16:11:54Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:42:33Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:42:33Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-01T16:11:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://c7d1187ca4b14b93ae158eb71c0f294ddc0f9701a098d9e87380f97fc443b511
    image: quay.io/jetstack/cert-manager-cainjector:v1.12.0
    imageID: quay.io/jetstack/cert-manager-cainjector@sha256:5cc751f8fde077e152c0119bb9fc0841d4f2c9ab8d69fb80ab538afd19c74044
    lastState: {}
    name: cert-manager-cainjector
    ready: true
    restartCount: 3
    started: true
    state:
      running:
        startedAt: "2024-02-15T09:42:32Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 192.168.0.42
  podIPs:
  - ip: 192.168.0.42
  qosClass: BestEffort
  startTime: "2024-02-01T16:11:54Z"
