apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: bb7304b67f927f92ac8e7d7571c37809f8cd6b218d420fbd7e383c40a6b9db50
    cni.projectcalico.org/podIP: 192.168.0.8/32
    cni.projectcalico.org/podIPs: 192.168.0.8/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.8"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.8"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-01-06T00:34:07Z"
  generateName: cert-manager-cainjector-bdd866bd4-
  labels:
    app: cainjector
    app.kubernetes.io/component: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/version: v1.12.0
    pod-template-hash: bdd866bd4
  name: cert-manager-cainjector-bdd866bd4-rpr7k
  namespace: cert-manager
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cert-manager-cainjector-bdd866bd4
    uid: 6a312387-9bf4-4f3a-8466-e4a7e5bba66f
  uid: 95ba3b9e-8507-4a8d-b43b-f8266e6b8e6f
spec:
  containers:
  - args:
    - --v=2
    - --leader-election-namespace=kube-system
    env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: quay.io/jetstack/cert-manager-cainjector:v1.12.0
    imagePullPolicy: IfNotPresent
    name: cert-manager-cainjector
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-x6kwx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: smane-csrx-new
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: cert-manager-cainjector
  serviceAccountName: cert-manager-cainjector
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-x6kwx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:34:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:34:16Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:34:16Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:34:07Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://e67861c11f931977067d18296c471715e26c7a9a12fa23ad4f6ea047c49e097e
    image: quay.io/jetstack/cert-manager-cainjector:v1.12.0
    imageID: quay.io/jetstack/cert-manager-cainjector@sha256:5cc751f8fde077e152c0119bb9fc0841d4f2c9ab8d69fb80ab538afd19c74044
    lastState: {}
    name: cert-manager-cainjector
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-06T00:34:15Z"
  hostIP: 10.87.76.26
  phase: Running
  podIP: 192.168.0.8
  podIPs:
  - ip: 192.168.0.8
  qosClass: BestEffort
  startTime: "2024-01-06T00:34:07Z"
