apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 700d9fe38746bf9faf68bc7b3b283a1828f680880016ff081067e67d230f4330
    cni.projectcalico.org/podIP: 10.244.100.200/32
    cni.projectcalico.org/podIPs: 10.244.100.200/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "10.244.100.200"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "10.244.100.200"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-01-15T18:12:06Z"
  generateName: coredns-756994469c-
  labels:
    k8s-app: kube-dns
    pod-template-hash: 756994469c
  name: coredns-756994469c-d5xlj
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-756994469c
    uid: 74e6b687-d3a4-4ebf-a785-4a997e73f3d9
  uid: 01eaa7b9-9806-4321-8173-3cd80a4e1f5c
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - kube-dns
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    image: registry.englab.juniper.net/jfrog-repo/hosted_docker_images/coredns:v1.10.1
    imagePullPolicy: IfNotPresent
    name: coredns
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    - containerPort: 9153
      name: metrics
      protocol: TCP
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - all
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8c7kh
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: sharmag-k8s-master-pnad30.englab.juniper.net
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns
  serviceAccountName: coredns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: coredns
    name: config-volume
  - name: kube-api-access-8c7kh
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-15T18:12:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-06T12:10:22Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-06T12:10:22Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-15T18:12:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://720614dcacb6926def5425ccf9d2d8465f22e4e9884d8e7837a068bd031b0b81
    image: registry.englab.juniper.net/jfrog-repo/hosted_docker_images/coredns:v1.10.1
    imageID: ead0a4a53df89fd173874b46093b6e62d8c72967bbf606d672c9e8c9b601a4fc
    lastState: {}
    name: coredns
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-02-06T12:10:22Z"
  hostIP: 192.168.1.2
  phase: Running
  podIP: 10.244.100.200
  podIPs:
  - ip: 10.244.100.200
  qosClass: Burstable
  startTime: "2024-01-15T18:12:06Z"
