apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 8758c96b7df47aeae94878f191b05804
    kubernetes.io/config.mirror: 8758c96b7df47aeae94878f191b05804
    kubernetes.io/config.seen: "2024-02-01T16:00:04.186734097Z"
    kubernetes.io/config.source: file
  creationTimestamp: "2024-02-01T16:00:04Z"
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-abhi-master-node
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: abhi-master-node
    uid: 97f82643-4df4-4c57-b0c4-dccb22168250
  uid: 3d5f71f3-d176-4db2-9ff1-eb529c2c72cc
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    image: registry.k8s.io/kube-scheduler:v1.27.10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: abhi-master-node
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:41:40Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:41:56Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:41:56Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:41:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://de20947ff58dd50de7772919b630626086aaa4ea9bc9a86d549bffc79267314c
    image: registry.k8s.io/kube-scheduler:v1.27.10
    imageID: registry.k8s.io/kube-scheduler@sha256:09294de61e63987f181077cbc2f5c82463878af9cd8ecc6110c54150c9ae3143
    lastState: {}
    name: kube-scheduler
    ready: true
    restartCount: 5
    started: true
    state:
      running:
        startedAt: "2024-02-15T09:41:41Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 10.87.76.24
  podIPs:
  - ip: 10.87.76.24
  qosClass: Burstable
  startTime: "2024-02-15T09:41:40Z"
