apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-06T00:21:37Z"
  generateName: kube-multus-ds-
  labels:
    app: multus
    controller-revision-hash: 5f7749fc79
    name: multus
    pod-template-generation: "1"
    tier: node
  name: kube-multus-ds-7ncnd
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: kube-multus-ds
    uid: ae865caa-c64c-4391-9ef9-cdcc90485968
  uid: 4c0b058a-ffe8-4442-8067-b35b896592f4
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - smane-csrx-new
  containers:
  - args:
    - --multus-conf-file=auto
    - --cni-version=0.3.1
    command:
    - /entrypoint.sh
    image: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.2
    imagePullPolicy: IfNotPresent
    name: kube-multus
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/etc/cni/net.d
      name: cni
    - mountPath: /host/opt/cni/bin
      name: cnibin
    - mountPath: /tmp/multus-conf
      name: multus-cfg
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5fjlc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: smane-csrx-new
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: multus
  serviceAccountName: multus
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: cni
  - hostPath:
      path: /opt/cni/bin
      type: ""
    name: cnibin
  - configMap:
      defaultMode: 420
      items:
      - key: cni-conf.json
        path: 70-multus.conf
      name: multus-cni-config
    name: multus-cfg
  - name: kube-api-access-5fjlc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:21:37Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:22:59Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:22:59Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:21:37Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://d1a8ce46c787ed2af738f29edc212e9efde807184d254293efdda219cd59d9fc
    image: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.2
    imageID: ghcr.io/k8snetworkplumbingwg/multus-cni@sha256:5565a69287eaa58dbcb405a4224e030a71f9af60db409036d31758de8610f2e9
    lastState: {}
    name: kube-multus
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-01-06T00:22:59Z"
  hostIP: 10.87.76.26
  phase: Running
  podIP: 10.87.76.26
  podIPs:
  - ip: 10.87.76.26
  qosClass: Guaranteed
  startTime: "2024-01-06T00:21:37Z"
