apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-12-27T09:47:05Z"
  generateName: kube-multus-ds-
  labels:
    app: multus
    controller-revision-hash: 5c99f97fdf
    name: multus
    pod-template-generation: "1"
    tier: node
  name: kube-multus-ds-kvhj4
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: kube-multus-ds
    uid: 7fe05ca2-5ee9-4a68-ad36-19f6a4e5b981
  uid: 106cfd03-50ca-4e15-978f-86797c14d6eb
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
  containers:
  - args:
    - --multus-conf-file=auto
    - --cni-version=0.3.1
    command:
    - /entrypoint.sh
    image: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.8
    imagePullPolicy: IfNotPresent
    name: kube-multus
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/etc/cni/net.d
      name: cni
    - mountPath: /host/opt/cni/bin
      name: cnibin
    - mountPath: /tmp/multus-conf
      name: multus-cfg
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bktbm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - command:
    - cp
    - /usr/src/multus-cni/bin/multus
    - /host/opt/cni/bin/multus
    image: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.8
    imagePullPolicy: IfNotPresent
    name: install-multus-binary
    resources:
      requests:
        cpu: 10m
        memory: 15Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/opt/cni/bin
      mountPropagation: Bidirectional
      name: cnibin
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bktbm
      readOnly: true
  nodeName: sharmag-k8s-dpdk-kubelet1-pnad30.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: multus
  serviceAccountName: multus
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: cni
  - hostPath:
      path: /opt/cni/bin
      type: ""
    name: cnibin
  - configMap:
      defaultMode: 420
      items:
      - key: cni-conf.json
        path: 70-multus.conf
      name: multus-cni-config
    name: multus-cfg
  - name: kube-api-access-bktbm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:47:12Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:47:13Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:47:13Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-12-27T09:47:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://e1b0aaa9e5cc864a246ef80e31e7b63ae88d069a78b08a914d7cbe97fe79e1a5
    image: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.8
    imageID: c65d3833b509f9769a2e37ee7c68d6fbe54a47540b19a436455a9ee596b41100
    lastState: {}
    name: kube-multus
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-12-27T09:47:12Z"
  hostIP: 192.168.1.3
  initContainerStatuses:
  - containerID: cri-o://6dc5445024d5708cb6fb001bea123b7e15a869a49ea5908ab371ca2d3e6e17c4
    image: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.8
    imageID: c65d3833b509f9769a2e37ee7c68d6fbe54a47540b19a436455a9ee596b41100
    lastState: {}
    name: install-multus-binary
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://6dc5445024d5708cb6fb001bea123b7e15a869a49ea5908ab371ca2d3e6e17c4
        exitCode: 0
        finishedAt: "2023-12-27T09:47:11Z"
        reason: Completed
        startedAt: "2023-12-27T09:47:11Z"
  phase: Running
  podIP: 192.168.1.3
  podIPs:
  - ip: 192.168.1.3
  qosClass: Burstable
  startTime: "2023-12-27T09:47:05Z"
