apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 82e6876b6442229897663188a629ae4ecffd98606418679384f8ab421ce564e2
    cni.projectcalico.org/podIP: 192.168.0.12/32
    cni.projectcalico.org/podIPs: 192.168.0.12/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.12"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.12"
          ],
          "default": true,
          "dns": {}
      }]
    prometheus.io/port: "7472"
    prometheus.io/scrape: "true"
  creationTimestamp: "2024-01-06T00:49:57Z"
  generateName: controller-595f88d88f-
  labels:
    app: metallb
    component: controller
    pod-template-hash: 595f88d88f
  name: controller-595f88d88f-kxch2
  namespace: metallb-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: controller-595f88d88f
    uid: 8a7dd4b7-5b94-4da3-804c-f45f7c92127d
  uid: 156e647b-1bcd-45f6-98e2-e304ed405c92
spec:
  containers:
  - args:
    - --port=7472
    - --log-level=info
    env:
    - name: METALLB_ML_SECRET_NAME
      value: memberlist
    - name: METALLB_DEPLOYMENT
      value: controller
    image: quay.io/metallb/controller:v0.13.10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: controller
    ports:
    - containerPort: 7472
      name: monitoring
      protocol: TCP
    - containerPort: 9443
      name: webhook-server
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: monitoring
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: cert
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dw5bk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: smane-csrx-new
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  serviceAccount: controller
  serviceAccountName: controller
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: cert
    secret:
      defaultMode: 420
      secretName: webhook-server-cert
  - name: kube-api-access-dw5bk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:49:57Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:50:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:50:17Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-06T00:49:57Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://4b089a2e9c93cfc47ad172d9d2b4effeaed8dd744e69b43dc78a496c12a542cc
    image: quay.io/metallb/controller:v0.13.10
    imageID: quay.io/metallb/controller@sha256:1b33357b3595468aac9d5b9115fc4d35fc475124551180956083294cdeeb94b6
    lastState: {}
    name: controller
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-06T00:50:01Z"
  hostIP: 10.87.76.26
  phase: Running
  podIP: 192.168.0.12
  podIPs:
  - ip: 192.168.0.12
  qosClass: BestEffort
  startTime: "2024-01-06T00:49:57Z"
