apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"webhook-service","namespace":"metallb-system"},"spec":{"ports":[{"port":443,"targetPort":9443}],"selector":{"component":"controller"}}}
  creationTimestamp: "2024-01-06T00:49:57Z"
  name: webhook-service
  namespace: metallb-system
  uid: a547cc52-fcc3-4a90-b672-dca448f6849e
spec:
  clusterIP: 10.100.200.254
  clusterIPs:
  - 10.100.200.254
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    component: controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
