apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 141407d4460bea7238ee2995fe3d518d1b257b1867d2d052ee4f8955eb679d6b
    cni.projectcalico.org/podIP: 192.168.0.1/32
    cni.projectcalico.org/podIPs: 192.168.0.1/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.1"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.1"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-15T09:57:09Z"
  generateName: katafygio-74f4f998f5-
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    pod-template-hash: 74f4f998f5
    release: katafygio
  name: katafygio-74f4f998f5-cwx29
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: katafygio-74f4f998f5
    uid: 3ee17f7e-4bb0-4067-8522-3774904969f4
  uid: fd18104d-651f-4d36-a755-001fe834672e
spec:
  containers:
  - args:
    - --healthcheck-port=8080
    - --log-level=info
    - --log-output=stdout
    - --resync-interval=300
    - --exclude-kind=replicasets
    - --exclude-kind=endpoints
    - --exclude-kind=events
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/katafygio-v3:CER-194
    imagePullPolicy: Always
    name: katafygio
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/katafygio
      name: katafygio-data
    - mountPath: /etc/katafygio
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zx746
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsUser: 65534
  serviceAccount: katafygio
  serviceAccountName: katafygio
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: katafygio-data
    persistentVolumeClaim:
      claimName: katafygio
  - configMap:
      defaultMode: 420
      name: katafygio-config
    name: config-volume
  - name: kube-api-access-zx746
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:57:09Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-16T14:42:55Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-16T14:42:55Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:57:09Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://9ca7635ea06863d49e88079d9c6ca214fdb9b101174a4cb70d0290772e71b2ba
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/katafygio-v3:CER-194
    imageID: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/katafygio-v3@sha256:bc704571caefbe45884e2fd6f3b5a2fcecdd1f0eff9a5701c2bf606d29447b7a
    lastState:
      terminated:
        containerID: cri-o://779361416f715dc87e9d25aba8867dec222e26db5208abe069bfc3f82a5688ea
        exitCode: 1
        finishedAt: "2024-02-16T14:42:43Z"
        reason: Error
        startedAt: "2024-02-16T14:37:12Z"
    name: katafygio
    ready: true
    restartCount: 242
    started: true
    state:
      running:
        startedAt: "2024-02-16T14:42:54Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 192.168.0.1
  podIPs:
  - ip: 192.168.0.1
  qosClass: BestEffort
  startTime: "2024-02-15T09:57:09Z"
