apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: ec765aee6c1817a97917fdbb1e54f6506b2fa21a14e42dfbccad452f08556f27
    cni.projectcalico.org/podIP: 192.168.0.47/32
    cni.projectcalico.org/podIPs: 192.168.0.47/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.47"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.47"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-14T09:04:32Z"
  generateName: gitea-69797b9b7b-
  labels:
    app: gitea
    pod-template-hash: 69797b9b7b
  name: gitea-69797b9b7b-7zgd4
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: gitea-69797b9b7b
    uid: 59b1964b-689a-4825-b3a3-3a5fef02f3e5
  uid: 1f51f5de-f6c4-4a67-a183-09623040cf54
spec:
  containers:
  - image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/gitea/gitea:1.21.4-rootless
    imagePullPolicy: IfNotPresent
    name: gitea
    ports:
    - containerPort: 3000
      name: gitea
      protocol: TCP
    - containerPort: 22
      name: git-ssh
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: git-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fm7kc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: git-volume
    persistentVolumeClaim:
      claimName: git-volume
  - name: kube-api-access-fm7kc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-14T09:04:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:42:19Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:42:19Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-14T09:04:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://0b1c58be67f1c31ad5fa98c8337f9b6f1c5e500671d14ab5ec3f01b0179e8bf7
    image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/gitea/gitea:1.21.4-rootless
    imageID: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/gitea/gitea@sha256:e881be33a508bc78c04e18aa167a449c4910f28ea11f25981abdc0ca47073fcd
    lastState: {}
    name: gitea
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-02-15T09:42:19Z"
  hostIP: 10.87.76.24
  phase: Running
  podIP: 192.168.0.47
  podIPs:
  - ip: 192.168.0.47
  qosClass: BestEffort
  startTime: "2024-02-14T09:04:35Z"
