apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: ffffc2cc2dbc931e03db1fe9b08f5d2cfeed6adb2c6f012b51101f807e425fa2
    cni.projectcalico.org/podIP: 192.168.0.15/32
    cni.projectcalico.org/podIPs: 192.168.0.15/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.15"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.15"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-15T09:49:47Z"
  generateName: katafygio-74f4f998f5-
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    pod-template-hash: 74f4f998f5
    release: katafygio
  name: katafygio-74f4f998f5-mskn4
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: katafygio-74f4f998f5
    uid: 2006dc6d-c5dd-45ec-a9e8-9370adf5dcaf
  uid: cfb1910f-a33f-4b80-9763-9a7b8011579c
spec:
  containers:
  - args:
    - --healthcheck-port=8080
    - --log-level=info
    - --log-output=stdout
    - --resync-interval=300
    - --exclude-kind=replicasets
    - --exclude-kind=endpoints
    - --exclude-kind=events
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/katafygio-v3:CER-194
    imagePullPolicy: Always
    name: katafygio
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/katafygio
      name: katafygio-data
    - mountPath: /etc/katafygio
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-v6wnq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: smane-csrx-new
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsUser: 65534
  serviceAccount: katafygio
  serviceAccountName: katafygio
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: katafygio-data
    persistentVolumeClaim:
      claimName: katafygio
  - configMap:
      defaultMode: 420
      name: katafygio-config
    name: config-volume
  - name: kube-api-access-v6wnq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:49:47Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T20:00:45Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T20:00:45Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-15T09:49:47Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://4face6bc8a08c9f68abb5afef325bec28878ab6f1d09f763d149c0ffcab4ecf4
    image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/katafygio-v3:CER-194
    imageID: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/katafygio-v3@sha256:bc704571caefbe45884e2fd6f3b5a2fcecdd1f0eff9a5701c2bf606d29447b7a
    lastState:
      terminated:
        containerID: cri-o://586288625e3611ae54e85de728b2bfa723496b605e569a6116fb8cff4f9b0c77
        exitCode: 1
        finishedAt: "2024-02-15T19:55:44Z"
        reason: Error
        startedAt: "2024-02-15T19:54:25Z"
    name: katafygio
    ready: true
    restartCount: 99
    started: true
    state:
      running:
        startedAt: "2024-02-15T20:00:44Z"
  hostIP: 10.87.76.26
  phase: Running
  podIP: 192.168.0.15
  podIPs:
  - ip: 192.168.0.15
  qosClass: BestEffort
  startTime: "2024-02-15T09:49:47Z"
