apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: ea2ba861b0aab601f259ecbd302c76c970fbbbc2ca732fe8a6b25327827f9173
    cni.projectcalico.org/podIP: 10.244.100.199/32
    cni.projectcalico.org/podIPs: 10.244.100.199/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "10.244.100.199"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "10.244.100.199"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-06T10:16:53Z"
  generateName: gitea-7c6954fdcd-
  labels:
    app: gitea
    pod-template-hash: 7c6954fdcd
  name: gitea-7c6954fdcd-mhtqj
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: gitea-7c6954fdcd
    uid: 88141cd5-3614-4a7a-a531-d713497cc344
  uid: 2872a3b6-350c-4cbf-868b-47143faf9554
spec:
  containers:
  - image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/gitea/gitea:1.21.4-rootless
    imagePullPolicy: IfNotPresent
    name: gitea
    ports:
    - containerPort: 3000
      name: gitea
      protocol: TCP
    - containerPort: 22
      name: git-ssh
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: git-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-h4psv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: sharmag-k8s-master-pnad30.englab.juniper.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: git-volume
    persistentVolumeClaim:
      claimName: git-volume
  - name: kube-api-access-h4psv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-06T10:17:04Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-06T12:10:16Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-06T12:10:16Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-06T10:17:04Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://5e384d36747be1736ea7ef02fdaf44a26b4e54b934003ddb3c00bc74a8581466
    image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/gitea/gitea:1.21.4-rootless
    imageID: b54bb0997f8c4c7a1bfc57640afe1b0c79065097e1e92889babcfaa6c18d6ae6
    lastState: {}
    name: gitea
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-02-06T12:10:16Z"
  hostIP: 192.168.1.2
  phase: Running
  podIP: 10.244.100.199
  podIPs:
  - ip: 10.244.100.199
  qosClass: BestEffort
  startTime: "2024-02-06T10:17:04Z"
